### ISSUE TITLE
NullPointerException on updateTextSize

### ISSUE THREAD

**Issue by felikjunvianto** [theDazzler/droidicon#30]
Hi, I recently stumbled upon a weird error saying NullPointerException on updateTextSize. Any suggestion or insight why this happen?

```
Fatal Exception: java.lang.NullPointerException: Attempt to get length of null array
       at com.thedazzler.droidicon.IconicFontDrawable.updateTextSize(IconicFontDrawable.java:245)
       at com.thedazzler.droidicon.IconicFontDrawable.draw(IconicFontDrawable.java:181)
       at android.widget.TextView.onDraw(TextView.java:5040)
       at android.view.View.draw(View.java:13560)
       at android.view.View.getDisplayList(View.java:12511)
       at android.view.View.getDisplayList(View.java:12555)
       at android.view.View.draw(View.java:13284)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2990)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2860)
       at android.view.View.getDisplayList(View.java:12509)
       at android.view.View.getDisplayList(View.java:12555)
       at android.view.View.draw(View.java:13284)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2990)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2860)
       at android.view.View.getDisplayList(View.java:12509)
       at android.view.View.getDisplayList(View.java:12555)
       at android.view.View.draw(View.java:13284)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2990)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2860)
       at android.view.View.getDisplayList(View.java:12509)
       at android.view.View.getDisplayList(View.java:12555)
       at android.view.View.draw(View.java:13284)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2990)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2860)
       at android.view.View.draw(View.java:13563)
       at android.widget.FrameLayout.draw(FrameLayout.java:467)
       at android.view.View.getDisplayList(View.java:12511)
       at android.view.View.getDisplayList(View.java:12555)
       at android.view.View.draw(View.java:13284)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2990)
       at android.widget.ListView.drawChild(ListView.java:3245)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2860)
       at android.widget.AbsListView.dispatchDraw(AbsListView.java:2631)
       at android.widget.ListView.dispatchDraw(ListView.java:3240)
       at android.view.View.draw(View.java:13563)
       at android.widget.AbsListView.draw(AbsListView.java:4219)
       at android.view.View.getDisplayList(View.java:12511)
       at android.view.View.getDisplayList(View.java:12555)
       at android.view.View.draw(View.java:13284)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2990)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2867)
       at android.view.View.draw(View.java:13563)
       at android.view.View.getDisplayList(View.java:12511)
       at android.view.View.getDisplayList(View.java:12555)
       at android.view.View.draw(View.java:13284)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2990)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2860)
       at android.view.View.getDisplayList(View.java:12509)
       at android.view.View.getDisplayList(View.java:12555)
       at android.view.View.draw(View.java:13284)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2990)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2860)
       at android.view.View.getDisplayList(View.java:12509)
       at android.view.View.getDisplayList(View.java:12555)
       at android.view.View.draw(View.java:13284)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2990)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2860)
       at android.view.View.getDisplayList(View.java:12509)
       at android.view.View.getDisplayList(View.java:12555)
       at android.view.View.draw(View.java:13284)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2990)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2860)
       at android.view.View.getDisplayList(View.java:12509)
       at android.view.View.getDisplayList(View.java:12555)
       at android.view.View.draw(View.java:13284)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2990)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2860)
       at android.view.View.getDisplayList(View.java:12509)
       at android.view.View.getDisplayList(View.java:12555)
       at android.view.View.draw(View.java:13284)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2990)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2860)
       at android.view.View.draw(View.java:13563)
       at android.widget.FrameLayout.draw(FrameLayout.java:467)
       at android.view.View.getDisplayList(View.java:12511)
       at android.view.View.getDisplayList(View.java:12555)
       at android.view.View.draw(View.java:13284)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2990)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2860)
       at android.view.View.getDisplayList(View.java:12509)
       at android.view.View.getDisplayList(View.java:12555)
       at android.view.View.draw(View.java:13284)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2990)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2860)
       at android.view.View.getDisplayList(View.java:12509)
       at android.view.View.getDisplayList(View.java:12555)
       at android.view.View.draw(View.java:13284)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2990)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2860)
       at android.view.View.getDisplayList(View.java:12509)
       at android.view.View.getDisplayList(View.java:12555)
       at android.view.View.draw(View.java:13284)
       at android.view.ViewGroup.drawChild(ViewGroup.java:2990)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2860)
       at android.view.View.draw(View.java:13563)
       at android.widget.FrameLayout.draw(FrameLayout.java:467)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2458)
       at android.view.View.getDisplayList(View.java:12511)
       at android.view.View.getDisplayList(View.java:12555)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1144)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2273)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2145)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1956)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1113)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4481)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
       at android.view.Choreographer.doCallbacks(Choreographer.java:555)
       at android.view.Choreographer.doFrame(Choreographer.java:525)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4867)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Thanks :)

**Comment by theDazzler** [comment]
@felikjunvianto Could you post your code?

**Comment by felikjunvianto** [comment]
@theDazzler Yes, is code snippet below sufficient?

```
public class TicketDetailAdapter extends ArrayAdapter<TicketItem> {
    private Context context;

    private IconicFontDrawable whatsAppPendingIcon, whatsAppSentIcon, whatsAppSentAllIcon, whatsAppSentSeenAllIcon, seenIcon, infoIcon;
    private ProgressDialog progressDialog;

    public TicketDetailAdapter(Context context, ArrayList<TicketItem> ticketItems) {
        super(context, 0, ticketItems);
        this.context = context;

        // prepare all necessary icons to be cached
        int grayColor = context.getResources().getColor(R.color.Gray);
        int iconSize10 = Utilities.dpToPixel(context, 10);
        int iconSize15 = Utilities.dpToPixel(context, 15);
        int iconSize20 = Utilities.dpToPixel(context, 20);

        whatsAppPendingIcon = new IconicFontDrawable(context);
        whatsAppPendingIcon.setIcon("gmd-alarm");
        whatsAppPendingIcon.setIconColor(grayColor);
        whatsAppPendingIcon.setIntrinsicHeight(iconSize20);
        whatsAppPendingIcon.setIntrinsicWidth(iconSize20);

        whatsAppSentIcon = new IconicFontDrawable(context);
        whatsAppSentIcon.setIcon("gmn-done");
        whatsAppSentIcon.setIconColor(grayColor);
        whatsAppSentIcon.setIntrinsicHeight(iconSize20);
        whatsAppSentIcon.setIntrinsicWidth(iconSize20);

        whatsAppSentAllIcon = new IconicFontDrawable(context);
        whatsAppSentAllIcon.setIcon("gmd-done-all");
        whatsAppSentAllIcon.setIconColor(grayColor);
        whatsAppSentAllIcon.setIntrinsicHeight(iconSize20);
        whatsAppSentAllIcon.setIntrinsicWidth(iconSize20);

        whatsAppSentSeenAllIcon = new IconicFontDrawable(context);
        whatsAppSentSeenAllIcon.setIcon("gmd-done-all");
        whatsAppSentSeenAllIcon.setIconColor(context.getResources().getColor(R.color.TwitterBlue));
        whatsAppSentSeenAllIcon.setIntrinsicHeight(iconSize20);
        whatsAppSentSeenAllIcon.setIntrinsicWidth(iconSize20);

        seenIcon = new IconicFontDrawable(context);
        seenIcon.setIcon("fa-check");
        seenIcon.setIconColor(context.getResources().getColor(R.color.Green));
        seenIcon.setIntrinsicHeight(iconSize10);
        seenIcon.setIntrinsicWidth(iconSize10);

        infoIcon = new IconicFontDrawable(context);
        infoIcon.setIcon("fa-info-circle");
        infoIcon.setIconColor(grayColor);
        infoIcon.setIntrinsicWidth(iconSize15);
        infoIcon.setIntrinsicHeight(iconSize15);
    }

    ...

    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        final TicketItem currTicketItem = getItem(position);
        if(DEBUG) Log.d("Render TicketItem", "at position = " + position + ", ticket item = " + currTicketItem);

        if(convertView == null) {
            int layoutType = -1;

            switch(getItemViewType(position)) {
                case TicketItem.TICKET_ITEM_POST_COMMENT: layoutType = R.layout.model_ticket_item_post_comment; break;
                case TicketItem.TICKET_ITEM_PRIVATE_NOTE: layoutType = R.layout.model_ticket_item_private_note; break;
                case TicketItem.TICKET_ITEM_NOTIFICATION: layoutType = R.layout.model_ticket_item_notification; break;
            }

            convertView = LayoutInflater.from(context).inflate(layoutType, parent, false);
        }

        if(getItemViewType(position) == TicketItem.TICKET_ITEM_POST_COMMENT) {
            
            ...

            TextView postSender = (TextView) convertView.findViewById(R.id.model_ticket_item_post_comment_text_post_sender);

            ...

            postSender.setCompoundDrawablesWithIntrinsicBounds(null, null, null, null);
            if("whatsapp".equals(currTicketItem.getChannel()) && currTicketItem.getUserId() != -1) {
                IconicFontDrawable statusIcon = null;

                switch(currTicketItem.getDeliveryStatus()) {
                    case "0": statusIcon = whatsAppPendingIcon; break;
                    case "1": statusIcon = whatsAppSentIcon; break;
                    case "2": statusIcon = whatsAppSentAllIcon; break;
                    case "3": statusIcon = whatsAppSentSeenAllIcon; break;
                }

                postSender.setCompoundDrawablesWithIntrinsicBounds(null, null, statusIcon, null);
            }

            ...

            TextView seenBy = (TextView) convertView.findViewById(R.id.model_ticket_item_post_comment_text_seen_by);

            if(!currTicketItem.getSeenBy().isEmpty()) {
                seenBy.setText(currTicketItem.getSeenBy());
                seenBy.setCompoundDrawablesWithIntrinsicBounds(seenIcon, null, null, null);
                seenBy.setVisibility(View.VISIBLE);
            } else {
                seenBy.setVisibility(View.GONE);
            }

            ...

        } else if(getItemViewType(position) == TicketItem.TICKET_ITEM_PRIVATE_NOTE) {
            
            ...

        } else {
            
            ...

            TextView postBodyMessage = (TextView) convertView.findViewById(R.id.model_ticket_item_notification_text_content_plaintext);
            
            ...

            postBodyMessage.setCompoundDrawablesWithIntrinsicBounds(infoIcon, null, null, null);
        }

        return convertView;
    }
}
```

(confidential codeblocks already been replaced by ellipsized character)

Frankly, I don't quite sure which part of the code that caused the error. After inspecting IconicFontDrawable implementation, updateTextSize() seems to be private method which cannot be called explicitly from the outside.

**Comment by felikjunvianto** [comment]
@theDazzler just tell me if you also need the layout xml code. Will provide as much as I can

**Comment by theDazzler** [comment]
@felikjunvianto do you know what line causes the error? It should tell you what line in the debugger

**Comment by theDazzler** [comment]
@felikjunvianto Do you ever do something like this: ```iconImageView.setImageDrawable(seenIcon);``` 
after you do this:
```
seenIcon = new IconicFontDrawable(context);
seenIcon.setIcon("fa-check");
seenIcon.setIconColor(context.getResources().getColor(R.color.Green));
seenIcon.setIntrinsicHeight(iconSize10);
seenIcon.setIntrinsicWidth(iconSize10);
```

**Comment by felikjunvianto** [comment]
@theDazzler unfortunately no. Android Studio debugger only showed the first 21 lines of the error stacktrace. Even Crashlytics only managed to capture error report from updateTextSize (detail can be found on http://crashes.to/s/6059c749aca).

No I don't think we ever use **setImageDrawable()** to utilize the IconicFontDawable object. Instead we use **setCompoundDrawablesWithIntrinsicBounds()**, for example (also shown in code snippet above):

```
...

TextView seenBy = (TextView) convertView.findViewById(R.id.model_ticket_item_post_comment_text_seen_by);

if(!currTicketItem.getSeenBy().isEmpty()) {
    seenBy.setText(currTicketItem.getSeenBy());
    seenBy.setCompoundDrawablesWithIntrinsicBounds(seenIcon, null, null, null);
    seenBy.setVisibility(View.VISIBLE);
} else {
    seenBy.setVisibility(View.GONE);
}

...
```

**Comment by felikjunvianto** [comment]
Hi, I think I have pinpointed the error source.

```
whatsAppSentIcon = new IconicFontDrawable(context);
whatsAppSentIcon.setIcon("gmn-done");
whatsAppSentIcon.setIconColor(grayColor);
whatsAppSentIcon.setIntrinsicHeight(iconSize20);
whatsAppSentIcon.setIntrinsicWidth(iconSize20);
```

The app always crash if I tried to render whatsAppSentIcon (icon using "gmd-done"). Changing to "gmd-check" is also not helping. Is "gmd-done" the right icon type string if I want to use (Google Material Design)[https://www.google.com/design/icons/], "done" icon?

**Comment by theDazzler** [comment]
@felikjunvianto you have "gmn-done", it should be "gmd-done"

**Comment by felikjunvianto** [comment]
@theDazzler my, that is really a blunder. Thank you pointing that out. I think this issue is safe to be closed.

In the future, it would be very helpful if we can have appropriate exception error message for mistyped icon type string. I will see what I can do to contribute in my spare time.
